name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.22'  # Set your Go version here

      - name: Build binary
        run: |
          go build -v -o memo

      - name: Build Linux amd64 binary
        run: GOOS=linux GOARCH=amd64 go build -v -o memo-linux-amd64

      - name: Build Windows amd64 binary
        run: GOOS=windows GOARCH=amd64 go build -v -o memo-windows-amd64.exe

      - name: Build macOS arm64 binary
        run: GOOS=darwin GOARCH=arm64 go build -v -o memo-darwin-arm64

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            memo-linux-amd64
            memo-windows-amd64.exe
            memo-darwin-arm64
